Package.swift
Sources/Authenticator/Extensions/Color+Utils.swift
Sources/Authenticator/Models/SignUpAttribute.swift
Sources/Authenticator/Theming/AuthenticatorTheme.swift
Sources/Authenticator/Utilities/AuthenticatorField.swift
Sources/Authenticator/Utilities/CountryUtils.swift
Sources/Authenticator/Utilities/Platform.swift
Sources/Authenticator/Views/ConfirmResetPasswordView.swift
Sources/Authenticator/Views/ConfirmSignInWithNewPasswordView.swift
Sources/Authenticator/Views/ConfirmSignUpView.swift
Sources/Authenticator/Views/ConfirmVerifyUserView.swift
Sources/Authenticator/Views/Internal/AuthenticatorMessageView.swift
Sources/Authenticator/Views/Internal/ConfirmSignInWithCodeView.swift
Sources/Authenticator/Views/Internal/SignUpInputField.swift
Sources/Authenticator/Views/Primitives/Button.swift
Sources/Authenticator/Views/Primitives/DatePicker.swift
Sources/Authenticator/Views/Primitives/ImageButton.swift
Sources/Authenticator/Views/Primitives/PasswordField.swift
Sources/Authenticator/Views/Primitives/PhoneNumberField.swift
Sources/Authenticator/Views/Primitives/TextField.swift
Sources/Authenticator/Views/ResetPasswordView.swift
Sources/Authenticator/Views/SignInView.swift
Sources/Authenticator/Views/SignUpView.swift

Adding support for macOS 💻 
Main changes:
- Wrapping OS-specific code in the corresponding`#if os` annotations
- Creating a `Platform` enum for easy runtime check of the platform
- Dropping the manual styling for `Button`s in favour of a `ButtonStyle`, which works on macOS as well (the old approach didn't)
- Tweaking some UX to match what is expected in a desktop OS. For example, always showing the "clear" buttons in TextFields
Finally, for both platforms: I've made a change so that if the "enter" key is pressed on the last input field in a view, the Authenticator should attempt to submit the operation without the user having to tap/click on the button.
----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

feat: Adding macOS support

---

Sources/Authenticator/Authenticator.swift
Sources/Authenticator/Configuration/AuthenticatorOptions.swift
Sources/Authenticator/Theming/AuthenticatorTheme.swift
Sources/Authenticator/Views/Internal/AuthenticatorView.swift
Sources/Authenticator/Views/ResetPasswordView.swift

This PR adds the ability to customize:
- The content associated with the `.loading` step, i.e. when the user session is being fetch at the beginning
- The blur intensity and content that is used by all the default views while an operation is in progress.
-  To support this I've removed the `loadingBlur` property from the `AuthenticatorTheme`, which is not really part of a theme if you think about it.
Misc changes:
- Removing leftover unnecessary `@escaping` annotations from the Authenticator's init
- Using the right `PhoneNumberField` view in the `ResetPasswordView`.

feat: Adding customization for Loading step and Busy states

---

Sources/Authenticator/Theming/AuthenticatorTheme.swift
Sources/Authenticator/Utilities/AuthenticatorField.swift
Sources/Authenticator/Utilities/Padding.swift
Sources/Authenticator/Views/ConfirmSignUpView.swift
Sources/Authenticator/Views/ErrorView.swift
Sources/Authenticator/Views/Internal/AuthenticatorMessageView.swift
Sources/Authenticator/Views/Internal/AuthenticatorView.swift
Sources/Authenticator/Views/Internal/DefaultHeader.swift
Sources/Authenticator/Views/Internal/SignUpInputField.swift
Sources/Authenticator/Views/Primitives/Button.swift
Sources/Authenticator/Views/Primitives/DatePicker.swift
Sources/Authenticator/Views/Primitives/PasswordField.swift
Sources/Authenticator/Views/Primitives/PhoneNumberField.swift
Sources/Authenticator/Views/Primitives/RadioButton.swift
Sources/Authenticator/Views/Primitives/TextField.swift
Sources/Authenticator/Views/SignInView.swift
Sources/Authenticator/Views/VerifyUserView.swift

**Description of changes**
This PR makes some changes to `AuthenticatorTheme` and its subtypes, based on the discussion with the UI team:
- Moving all variables names to `camelCase`
- Restructuring and renaming to closely match [existing Amplify UI theming solutions](https://github.com/aws-amplify/amplify-ui/tree/main/packages/ui/src/theme/tokens).
```
AuthenticatorTheme
├── components
│   └── authenticator
│       └── ...
│   └── button
│       └── ...
│   └── field
│       └── ...
│   └── alert
│       └── ...
│ 
├── fonts
│   └── ...
│ 
├── colors
│   └── foreground
│       └── ...
│   └── background
│       └── ...
│   └── border
│       └── ...
│
```
- Removing the `Style` struct and integrating its properties into the corresponding components.
- Making all `padding` variables to be …

feat: Finalizing Theming capabilities.

---

Sources/Authenticator/Resources/en.lproj/Localizable.strings
Sources/Authenticator/Utilities/RegionUtils.swift
Sources/Authenticator/Views/Primitives/PhoneNumberField.swift

- Adding the following missing region codes and their calling codes: `AQ`, `AX`, `BV`, `EH`, `HM`, `SS`, `TF`.
- Splitting `AN` into `BQ`, `CW` and `SX`, to match the current ISO 3166 definition.
- Using the term "Region" instead across the code, to be more accurate to what they represent.

fix: Adding missing calling codes

---

Sources/Authenticator/Configuration/AmplifyConfiguration.swift
Sources/Authenticator/States/SignUpState.swift
Tests/AuthenticatorTests/Mocks/MockAuthenticationService.swift
Tests/AuthenticatorTests/States/SignUpStateTests.swift

https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/17
When the using `EMAIL` or `PHONE_NUMBER` as `usernameAttributes` in Cognito's configuration, the Authenticator was not properly using it as a `username` when calling `Amplify.Auth.signUp(username:password:)`.
This PR fixes that by grabbing the right value from the list of attributes when it applies.

fix: Setting the right username value when using EMAIL or PHONE_NUMBER as usernameAttributes in Cognito

---

Sources/Authenticator/Utilities/RegionUtils.swift
Sources/Authenticator/Views/Primitives/PhoneNumberField.swift

- Instead of having to manually type a region's dialling code, we now show a sheet with a list of regions, their flags and dialling codes, allowing to search within it
- Replacing the hardcoded `127397` with a proper calculated value when converting the region code to its flag emoji.

feat: Adding dialling code picker to PhoneNumberField

---

Sources/Authenticator/Utilities/RegionUtils.swift

Using `String.compare(_:locale:) == .orderedAscending` instead of just `<` so that accented vowels are properly sorted.
E.g.: Following an alphabetical order, "Åland Islands" should be displayed before than "Bahamas". However:
```swift
"Åland Islands" < "Bahamas" // false
"Åland Islands".compare("Bahamas", locale: Locale.current) == .orderedAscending // true
```

fix: Fixing the sorting function used in the list of regions

---

Sources/Authenticator/Views/Internal/SignUpInputField.swift

*Description of changes:*
Fixes a compilation error when compiling with Xcode 15 beta (15A5160n).
Error on line 75 of `SignUpInputField.swift`, `Type 'any View' cannot conform to 'View'`. It seems that for some reason the `AnyView` initializer doesn't like the return type of `onChange(of:)` in this context anymore. Moving the `onChange(of:)` and `onAppear` modifiers outside of the `AnyView` resolves the error.

fix: Xcode 15 beta compilation error

---

Sources/Authenticator/Constants/ComponentInformation.swift
Sources/Authenticator/States/SignUpState.swift
Sources/Authenticator/Views/Primitives/PhoneNumberField.swift

This PR fixes the following issues on fields that are displayed in the Sign Up view:
- Removes any duplicated field in the array provided to `configure(with signUpFields:)`
- Avoids attempting to save an incomplete phone number if only the calling code is selected.
I'm also updating the `ComponentInformation.version`, which was still using the old `dev-preview` value.

fix: Fixing issues with Sign Up fields

---

CHANGELOG.md
Sources/Authenticator/Constants/ComponentInformation.swift
Sources/Authenticator/Views/Primitives/DatePicker.swift

- https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/30
When a `DatePicker` field was used (e.g. for the `birthDate` sign up field), the `ISO8601DateFormatter` that is used to parse the Date back to a String by defaults includes the time information as well.
This value was then rejected by Cognito as invalid, as they expect the date to be
> represented as an [ISO 8601:2004](https://openid.net/specs/openid-connect-core-1_0.html#ISO8601-2004) [ISO8601‑2004] `YYYY-MM-DD` format
This PR fixes this issue by setting the `.withFullDate` format options, which results in only the date being parsed to a string.
Additionally, I'm adding a `CHANGELOG.md` file with the past changes.
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

fix(DatePicker): Fixing the format used to parse the date into a string

---

CHANGELOG.md
Sources/Authenticator/Constants/ComponentInformation.swift
Sources/Authenticator/Views/Internal/SignUpInputField.swift

If a `label` was provided when creating a `.custom(...)` sign up field, it was never being displayed when rendered.
This PR fixes that. I'm also setting the `spacing` in the field's `Vstack` to match the other components.

fix: Adding missing label when displaying a `.custom()` Sign Up field

---

Sources/Authenticator/Models/SignUpAttribute.swift
Sources/Authenticator/Models/SignUpField.swift
Sources/Authenticator/States/SignUpState.swift
Sources/Authenticator/Views/Internal/SignUpInputField.swift

**Issue**
- https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/33
The `signUpAttributes` array in the Amplify configuration lists all the **required** attributes in the Cognito User Pool, but the Authenticator was not treating them as such.
This PR makes the following changes:
- Ensures that all attributes in `signupAttributes` are marked as **required**
- Tweaking `SignUpState.Field`, `BaseSignUpField` and `CustomSignUpField` in order to support this, but with no public API change.
- When the customer provides sign up fields, we now make the following validations:
- That required fields are marked as such (e.g. if a user sets a `birthDate(isRequired: false)` but `BIRTHDATE` is in `signUpAttributes`, we're going to overwrite it as required).
- …

fix(SignUpAttribute): Fixing required sign up attributes being rendered as optional

---

CHANGELOG.md
Package.resolved
Package.swift
Sources/Authenticator/Constants/ComponentInformation.swift
Sources/Authenticator/Models/AuthenticatorState.swift
Sources/Authenticator/States/AuthenticatorBaseState.swift
Tests/AuthenticatorTests/Mocks/MockAuthenticationService.swift

This PR unpins the Amplify version and makes the necessary code changes in order to compile.
**⚠️ Note:** TOTP support (introduced in [Amplify 2.16.0](https://github.com/aws-amplify/amplify-swift/releases/tag/2.16.0)) is **not** yet supported.
This PR also fixes an issue when calling `AuthenticatorState.setCurrentStep(_:)` when the current state is `.error`: The if condition was not checking the _current_ step value.
---

chore: Upgrading to Amplify 2.16+

---

Package.resolved
Sources/Authenticator/States/VerifyUserState.swift
Tests/AuthenticatorTests/Mocks/MockAuthenticationService.swift
Tests/AuthenticatorTests/States/VerifyUserStateTests.swift

This PR updates the `VerifyUserState` class to invoke Auth's new `sendVerificationCode` method instead of the now deprecated `resendConfirmationCode`.
Also adding the missing conformance to `MockAuthenticationService` so that the tests can compile and run.
---

chore: Using new sendVerificationCode API.

---

Sources/Authenticator/Views/Primitives/PhoneNumberField.swift

- https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/55
[Cognito's expectations](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#cognito-user-pools-standard-attributes) for a phone number is to be fully numerical except for the initial `+` sign. 
Although the **Authenticator's** Phone Number Field only shows the **numeric** keyboard for manual input, it's still possible to end up with non-numeric characters by using the **Auto-Fill** option, or simply by pasting a phone number from the clipboard.
The problem is that phone numbers are typically formatted in a way that include hyphens, spaces and parentheses (e.g. `+1 (123) 456-7890` instead of just `+11234567890`). So …

fix: Auto-filled phone numbers contain characters rejected by Cognito

---

Sources/Authenticator/Authenticator.swift
Sources/Authenticator/States/ConfirmSignUpState.swift

- https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/62
When the Authenticator is in the `.confirmSignUp` step and a new confirmation code is sent through `state.sendCode()`, `state.deliveryDetails` was not updated with the new information.

fix(ConfirmSignUp): Updating the state's `deliveryDetails` property when a new code is sent

---

Sources/Authenticator/Models/AuthenticatorState.swift
Sources/Authenticator/Models/AuthenticatorStep.swift

- https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/64
`AuthenticatorState.move(to:)` was meant to be `public` in order to allow developers of customized views to navigate through the initial steps, but it was `internal` instead.

fix: Making `AuthenticatorState.move(to:)` public

---

Sources/Authenticator/Utilities/PreviewFactory.swift

- https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/63
This PR introduces a `PreviewFactory` that provides developers with empty and no-op `States` that can be used in Xcode's `Previews` when implementing customized views.
For example:
```swift
import Authenticator
struct CustomSignInView: View {
@ObservedObject var state: SignInState
var body: some View { /*...*/ }
}
#Preview {
CustomSignInView(
state: PreviewFactory.States.signIn()
)
}
```

chore: Adding Factory for empty and no-op States that can be used in SwiftUI's previews.

---

CHANGELOG.md
Sources/Authenticator/Constants/ComponentInformation.swift

Updating the CHANGELOG and the `ComponentInformation.version` property in preparation for release 1.1.2

chore: Release 1.1.2 [skip ci]

---

.github/workflows/unit_tests.yml
Sources/Authenticator/States/SignUpState.swift

- https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/71
When a Sign Up flows is successful, the Authenticator automatically determines the next action based on the result's `nextStep`.
If a user doesn't need confirmation, the next step will be `done`, in which case the Authenticator will attempt to automatically Sign In.
However, because the user credentials were not yet set, the sign in request failed because it provided empty values.
***Other changes***
- Fixing the upload of coverage by providing the Codecov Token.
----

fix: Sign in fails when user is auto confirmed after sign up

---

CHANGELOG.md
Package.resolved
Package.swift

This PR pins the Amplify version up to 2.34.x, due to an internal change in 2.35.0 that needs to be addressed.
Also updating the CHANGELOG with the latest release.
---

chore: Pinning Amplify version up to 2.34.x

---

CHANGELOG.md
Package.resolved
Package.swift
Sources/Authenticator/Models/AuthenticatorState.swift
Sources/Authenticator/States/AuthenticatorBaseState.swift

- https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/79
This PR adds some logic to identify connectivity errors and display the proper error message, instead of defaulting to the generic unknown error.
*Additional changes:*
- Updated the code to support Amplify 2.35+ and update the code accordingly.
---

fix: Displaying the correct message on connectivity errors

---

CHANGELOG.md
Sources/Authenticator/Configuration/AmplifyConfiguration.swift
Sources/Authenticator/Constants/ComponentInformation.swift
Sources/Authenticator/Models/AuthenticatorState.swift
Tests/AuthenticatorTests/Mocks/MockAuthenticatorState.swift

- https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/86
When a user session cannot be refreshed, `Amplify.Auth.fetchAuthSession()` will still return `isSignedIn: true`, but attempting to perform any operation that requires authentication will subsequently fail and ask the user to log in again.
This is a known thing within Amplify, but can be handled by the Authenticator by signing out the user if we detect their session has expired when the component is launched. 
This PR proposes validating that a session has valid identity ID and/or Cognito tokens, depending on what type of configuration the user is using:
- If they only have `CognitoIdentity`, only check for a valid `session.getIdentityId()
- If they only have …

fix(Authenticator): Handling expired sessions

---

CHANGELOG.md
Sources/Authenticator/Authenticator.swift
Sources/Authenticator/Constants/ComponentInformation.swift
Sources/Authenticator/States/AuthenticatorBaseState.swift
Sources/Authenticator/Views/ConfirmResetPasswordView.swift
Sources/Authenticator/Views/ConfirmSignInWithCustomChallengeView.swift
Sources/Authenticator/Views/ConfirmSignInWithMFACodeView.swift
Sources/Authenticator/Views/ConfirmSignInWithNewPasswordView.swift
Sources/Authenticator/Views/ConfirmSignInWithTOTPCodeView.swift
Sources/Authenticator/Views/ConfirmSignUpView.swift
Sources/Authenticator/Views/ConfirmVerifyUserView.swift
Sources/Authenticator/Views/ContinueSignInWithMFASelectionView.swift
Sources/Authenticator/Views/ContinueSignInWithTOTPSetupView.swift
Sources/Authenticator/Views/Internal/ConfirmSignInWithCodeView.swift
Sources/Authenticator/Views/ResetPasswordView.swift
Sources/Authenticator/Views/SignInView.swift
Sources/Authenticator/Views/SignUpView.swift
Sources/Authenticator/Views/VerifyUserView.swift
Tests/AuthenticatorTests/States/AuthenticatorBaseStateTests.swift

This PR allows Authenticator customers to invoke the `errorMap(_:)` view modifiers without having to provide an `AuthenticatorError` for every possible `AuthError`. Instead, they can just provide a new value only for the errors they want to overwrite and return `nil` for all the rest, in which case the Authenticator will proceed to handle them with their default behaviour. 
For example, if a user only wants to override the message for `. notAuthorized` when a specific condition is met, they can now do something like:
```swift
Authenticator { _ in 
// ....
}
.errorMap { error in
if case .notAuthorized = error, anotherCondition {
return .error(message: "A custom message for .notAuthorized")
}
return nil
}
```
By submitting this pull request, I confirm that you …

fix(Authenticator): Allowing to only override the desired errors when invoking the errorMap functions

---

CHANGELOG.md
Sources/Authenticator/Constants/ComponentInformation.swift
Sources/Authenticator/Resources/en.lproj/Localizable.strings
Sources/Authenticator/States/AuthenticatorBaseState.swift
Tests/AuthenticatorTests/States/AuthenticatorBaseStateTests.swift

- https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/83
- https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/92
This PR adds new localization entries for the following errors coming from Cognito:
- `LimitExceededException`, mapped to a `AWSCognitoAuthError.limitExceeded` by Amplify
- `NotAuthorizedException` with a message of `"Password attempts exceeded"`, mapped to a `AuthError.notAuthorized` by Amplify.

fix(Authenticator): Adding new error localizations for limits exceeded

---

CHANGELOG.md
Sources/Authenticator/Extensions/AuthError+Connectivity.swift
Sources/Authenticator/Models/AuthenticatorState.swift
Sources/Authenticator/States/AuthenticatorBaseState.swift

- https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/103
This PRs fixes the issue when the access token is expired on launch but the device has no connectivity. 
Instead of just signing out the user, we'll keep them signed in. This is only done when the user was already signed in.

fix: Avoiding signing out users when the token refresh fails due to no connectivity
